/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    CustomDatePicker: typeof import('./src/components/CustomDatePicker.vue')['default']
    DataTableContextMenu: typeof import('./src/components/DataTableContextMenu.vue')['default']
    DialogCard: typeof import('./src/components/DialogCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingDialog: typeof import('./src/components/SettingDialog.vue')['default']
  }
}
